### ISSUE TITLE
Errors When Running Yarn

### ISSUE THREAD

**Issue by pacarvalho** [inlightmedia/react-zendesk-chat#3]
**Issue**

When I attempt to run `yarn` I get some ESLint errors as shown below. 

![image](https://user-images.githubusercontent.com/860599/66260445-c0f17c80-e78c-11e9-8e70-c683c1abc270.png)

I was able to resolve the errors by adding `"no-extra-semi": 1` to the rules in https://github.com/inlightmedia/react-zendesk-chat/blob/master/.eslintrc and adding `/*global $zopim*/` at the top of https://github.com/inlightmedia/react-zendesk-chat/blob/master/src/ReactZenDeskChat/ReactZenDeskChat.js

However, `yarn` still fails due to failing tests (see below) which is expected since https://github.com/inlightmedia/react-zendesk-chat/blob/master/src/ReactZenDeskChat/ReactZenDeskChat.test.js does not pass `appID` to the components upon creation. 

```bash
 FAIL  src/ReactZenDeskChat/ReactZenDeskChat.test.js
  MyComponent
    ✕ renders without crashing (51ms)
    ✕ should render name from prop (6ms)

  ● MyComponent › renders without crashing

    Error: Cannot initialize the ZenDesk Chat Component. Have you forgotten to pass in the appID prop?

      32 |              if (!appID){
      33 |                      console.error('Error: Have you forgotten to pass in hte appID prop?');
    > 34 |                      throw new Error('Error: Cannot initialize the ZenDesk Chat Component. Have you forgotten to pass in the appID prop?');
         |                            ^
      35 |                      return;
      36 |              } else if(!canUseDOM) {
      37 |                      console.error('Error: Could not initialize Zendesk react. The DOM is not ready.');

      at new ZenDeskChat (src/ReactZenDeskChat/ReactZenDeskChat.js:34:10)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:815:26)
      at render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:666:53)
      at fn (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:666:18)
      at new render (node_modules/enzyme/src/ShallowWrapper.js:397:22)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (src/ReactZenDeskChat/ReactZenDeskChat.test.js:7:21)

  ● MyComponent › should render name from prop

    Error: Cannot initialize the ZenDesk Chat Component. Have you forgotten to pass in the appID prop?

      32 |              if (!appID){
      33 |                      console.error('Error: Have you forgotten to pass in hte appID prop?');
    > 34 |                      throw new Error('Error: Cannot initialize the ZenDesk Chat Component. Have you forgotten to pass in the appID prop?');
         |                            ^
      35 |                      return;
      36 |              } else if(!canUseDOM) {
      37 |                      console.error('Error: Could not initialize Zendesk react. The DOM is not ready.');

      at new ZenDeskChat (src/ReactZenDeskChat/ReactZenDeskChat.js:34:10)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:815:26)
      at render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:666:53)
      at fn (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:666:18)
      at new render (node_modules/enzyme/src/ShallowWrapper.js:397:22)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (src/ReactZenDeskChat/ReactZenDeskChat.test.js:12:21)

  console.error node_modules/prop-types/checkPropTypes.js:20
    Warning: Failed prop type: The prop `appID` is marked as required in `ZenDeskChat`, but its value is `undefined`.
        in ZenDeskChat

  console.error src/ReactZenDeskChat/ReactZenDeskChat.js:33
    Error: Have you forgotten to pass in hte appID prop?

  console.error src/ReactZenDeskChat/ReactZenDeskChat.js:33
    Error: Have you forgotten to pass in hte appID prop?
```

Furthermore, running `yarn start` yields another error:

```bash
yarn run v1.16.0
$ webpack-dev-server --config examples/webpack.config.live.babel.js
.../@babel/core/lib/config/files/plugins.js:152
    throw e;
    ^

Error: Cannot find module 'babel-preset-react'
```

**Question**
Am I doing something wrong or did something happen to the package? 

I am attempting to run it locally in order to make a PR that adds some functionality (add ability to set additional properties such as name, email, phone, tags, etc. Maybe by allowing passing of an object param that would be passed into `set` https://api.zopim.com/files/meshim/widget/controllers/LiveChatAPI-js.html#set).

**Comment by inlightmedia** [comment]
Thanks for the question @pacarvalho! We are using this in production and it works great. I based it off a quick npm starter template so the example app in github repo does not work and never has (sadly the tests were from the template as well and do not work). The actual plugin works but the sample app does not unfortunately. It should work when you implement it in your code. I've done all my testing of this in my actual app to save time (not the best way to go about it but it allowed me to share something hopefully useful). If your actual implementation is not working feel free to shoot me some questions and I can maybe help troubleshoot or if you have ideas or PRs such as the one you suggested above those are welcome. You just won't be able to use the sample app in the repo to test yet because I couldn't put any time into making it work.

It looks like there are three issues here:
1. the linting problems
2. the failing tests
3. the requested feature for passing in an object

I'll add those to my todo list but in the mean time if you solve any of them and want to send a PR that would be more than welcome! Thanks for getting in touch!

**Comment by inlightmedia** [comment]
Failing Tests:
I fixed all the broken tests

Linting Problems:
I also fixed the eslint errors. 

Example App for Live Testing:
I removed the boilerplate example and added a working example of the component that can be built using npm run build-examples and run using npm run start.

**Comment by inlightmedia** [comment]
If you want to make that PR feel free. Sorry for the delay!
